//! COR24 instruction encoding tables
//! Auto-generated from dis_rom.v - do not edit manually
//!
//! Generated by: scripts/extract_decode_rom.py
//! Provides reverse mapping: (opcode, ra, rb) -> instruction byte

use crate::cpu::instruction::Opcode;

/// Encode instruction to byte. Returns None if encoding not found.
/// For single-byte instructions, returns the opcode byte.
/// For multi-byte instructions, returns the first byte (opcode + register info).
pub fn encode_instruction(opcode: Opcode, ra: u8, rb: u8) -> Option<u8> {
    let ra = ra & 0x07;
    let rb = rb & 0x07;
    
    match opcode {
        Opcode::AddReg => match (ra, rb) {
            (0, 0) => Some(0x00), // r0,r0
            (0, 1) => Some(0x01), // r0,r1
            (0, 2) => Some(0x02), // r0,r2
            (0, 3) => Some(0x58), // r0,fp
            (1, 0) => Some(0x03), // r1,r0
            (1, 1) => Some(0x04), // r1,r1
            (1, 2) => Some(0x05), // r1,r2
            (1, 3) => Some(0x5C), // r1,fp
            (2, 0) => Some(0x06), // r2,r0
            (2, 1) => Some(0x07), // r2,r1
            (2, 2) => Some(0x08), // r2,r2
            (2, 3) => Some(0x60), // r2,fp
            _ => None,
        },
        Opcode::AddImm => match (ra, rb) {
            (0, 7) => Some(0x09), // r0,r7
            (1, 7) => Some(0x0A), // r1,r7
            (2, 7) => Some(0x0B), // r2,r7
            (4, 7) => Some(0x0C), // sp,r7
            _ => None,
        },
        Opcode::And => match (ra, rb) {
            (0, 1) => Some(0x0D), // r0,r1
            (0, 2) => Some(0x0E), // r0,r2
            (1, 0) => Some(0x0F), // r1,r0
            (1, 2) => Some(0x10), // r1,r2
            (2, 0) => Some(0x11), // r2,r0
            (2, 1) => Some(0x12), // r2,r1
            _ => None,
        },
        Opcode::Bra => match (ra, rb) {
            (7, 7) => Some(0x13), // r7,r7
            _ => None,
        },
        Opcode::Brf => match (ra, rb) {
            (7, 7) => Some(0x14), // r7,r7
            _ => None,
        },
        Opcode::Brt => match (ra, rb) {
            (7, 7) => Some(0x15), // r7,r7
            _ => None,
        },
        Opcode::Ceq => match (ra, rb) {
            (0, 1) => Some(0x16), // r0,r1
            (0, 2) => Some(0x17), // r0,r2
            (0, 5) => Some(0xC8), // r0,z
            (1, 2) => Some(0x18), // r1,r2
            (1, 5) => Some(0xC9), // r1,z
            (2, 5) => Some(0xCA), // r2,z
            _ => None,
        },
        Opcode::Cls => match (ra, rb) {
            (0, 1) => Some(0x19), // r0,r1
            (0, 2) => Some(0x1A), // r0,r2
            (0, 5) => Some(0xCB), // r0,z
            (1, 0) => Some(0x1B), // r1,r0
            (1, 2) => Some(0x1C), // r1,r2
            (1, 5) => Some(0xCC), // r1,z
            (2, 0) => Some(0x1D), // r2,r0
            (2, 1) => Some(0x1E), // r2,r1
            (2, 5) => Some(0xCD), // r2,z
            _ => None,
        },
        Opcode::Clu => match (ra, rb) {
            (0, 1) => Some(0x1F), // r0,r1
            (0, 2) => Some(0x20), // r0,r2
            (1, 0) => Some(0x21), // r1,r0
            (1, 2) => Some(0x22), // r1,r2
            (2, 0) => Some(0x23), // r2,r0
            (2, 1) => Some(0x24), // r2,r1
            (5, 0) => Some(0xCE), // z,r0
            (5, 1) => Some(0xCF), // z,r1
            (5, 2) => Some(0xD0), // z,r2
            _ => None,
        },
        Opcode::Jal => match (ra, rb) {
            (1, 0) => Some(0x25), // r1,r0
            (1, 1) => Some(0xD1), // r1,r1
            (1, 2) => Some(0xD2), // r1,r2
            _ => None,
        },
        Opcode::Jmp => match (ra, rb) {
            (0, 7) => Some(0x26), // r0,r7
            (1, 7) => Some(0x27), // r1,r7
            (2, 7) => Some(0x28), // r2,r7
            (7, 7) => Some(0x68), // r7,r7
            _ => None,
        },
        Opcode::La => match (ra, rb) {
            (0, 7) => Some(0x29), // r0,r7
            (1, 7) => Some(0x2A), // r1,r7
            (2, 7) => Some(0x2B), // r2,r7
            (7, 7) => Some(0xC7), // r7,r7
            _ => None,
        },
        Opcode::Lb => match (ra, rb) {
            (0, 0) => Some(0x2C), // r0,r0
            (0, 1) => Some(0x2D), // r0,r1
            (0, 2) => Some(0x2E), // r0,r2
            (0, 3) => Some(0x2F), // r0,fp
            (1, 0) => Some(0x30), // r1,r0
            (1, 1) => Some(0x31), // r1,r1
            (1, 2) => Some(0x32), // r1,r2
            (1, 3) => Some(0x33), // r1,fp
            (2, 0) => Some(0x34), // r2,r0
            (2, 1) => Some(0x35), // r2,r1
            (2, 2) => Some(0x36), // r2,r2
            (2, 3) => Some(0x37), // r2,fp
            _ => None,
        },
        Opcode::Lbu => match (ra, rb) {
            (0, 0) => Some(0x38), // r0,r0
            (0, 1) => Some(0x39), // r0,r1
            (0, 2) => Some(0x3A), // r0,r2
            (0, 3) => Some(0x3B), // r0,fp
            (1, 0) => Some(0x3C), // r1,r0
            (1, 1) => Some(0x3D), // r1,r1
            (1, 2) => Some(0x3E), // r1,r2
            (1, 3) => Some(0x3F), // r1,fp
            (2, 0) => Some(0x40), // r2,r0
            (2, 1) => Some(0x41), // r2,r1
            (2, 2) => Some(0x42), // r2,r2
            (2, 3) => Some(0x43), // r2,fp
            _ => None,
        },
        Opcode::Lc => match (ra, rb) {
            (0, 7) => Some(0x44), // r0,r7
            (1, 7) => Some(0x45), // r1,r7
            (2, 7) => Some(0x46), // r2,r7
            _ => None,
        },
        Opcode::Lcu => match (ra, rb) {
            (0, 7) => Some(0x47), // r0,r7
            (1, 7) => Some(0x48), // r1,r7
            (2, 7) => Some(0x49), // r2,r7
            _ => None,
        },
        Opcode::Lw => match (ra, rb) {
            (0, 0) => Some(0x4A), // r0,r0
            (0, 1) => Some(0x4B), // r0,r1
            (0, 2) => Some(0x4C), // r0,r2
            (0, 3) => Some(0x4D), // r0,fp
            (1, 0) => Some(0x4E), // r1,r0
            (1, 1) => Some(0x4F), // r1,r1
            (1, 2) => Some(0x50), // r1,r2
            (1, 3) => Some(0x51), // r1,fp
            (2, 0) => Some(0x52), // r2,r0
            (2, 1) => Some(0x53), // r2,r1
            (2, 2) => Some(0x54), // r2,r2
            (2, 3) => Some(0x55), // r2,fp
            _ => None,
        },
        Opcode::Mov => match (ra, rb) {
            (0, 1) => Some(0x56), // r0,r1
            (0, 2) => Some(0x57), // r0,r2
            (0, 4) => Some(0x59), // r0,sp
            (0, 5) => Some(0x62), // r0,z
            (1, 0) => Some(0x5A), // r1,r0
            (1, 2) => Some(0x5B), // r1,r2
            (1, 4) => Some(0x5D), // r1,sp
            (1, 5) => Some(0x63), // r1,z
            (2, 0) => Some(0x5E), // r2,r0
            (2, 1) => Some(0x5F), // r2,r1
            (2, 4) => Some(0x61), // r2,sp
            (2, 5) => Some(0x64), // r2,z
            (3, 4) => Some(0x65), // fp,sp
            (4, 0) => Some(0x66), // sp,r0
            (4, 3) => Some(0x69), // sp,fp
            (6, 0) => Some(0x67), // r6,r0
            _ => None,
        },
        Opcode::Mul => match (ra, rb) {
            (0, 0) => Some(0x6A), // r0,r0
            (0, 1) => Some(0x6B), // r0,r1
            (0, 2) => Some(0x6C), // r0,r2
            (1, 0) => Some(0x6D), // r1,r0
            (1, 1) => Some(0x6E), // r1,r1
            (1, 2) => Some(0x6F), // r1,r2
            (2, 0) => Some(0x70), // r2,r0
            (2, 1) => Some(0x71), // r2,r1
            (2, 2) => Some(0x72), // r2,r2
            _ => None,
        },
        Opcode::Or => match (ra, rb) {
            (0, 1) => Some(0x73), // r0,r1
            (0, 2) => Some(0x74), // r0,r2
            (1, 0) => Some(0x75), // r1,r0
            (1, 2) => Some(0x76), // r1,r2
            (2, 0) => Some(0x77), // r2,r0
            (2, 1) => Some(0x78), // r2,r1
            _ => None,
        },
        Opcode::Pop => match (ra, rb) {
            (0, 4) => Some(0x79), // r0,sp
            (1, 4) => Some(0x7A), // r1,sp
            (2, 4) => Some(0x7B), // r2,sp
            (3, 4) => Some(0x7C), // fp,sp
            _ => None,
        },
        Opcode::Push => match (ra, rb) {
            (0, 4) => Some(0x7D), // r0,sp
            (1, 4) => Some(0x7E), // r1,sp
            (2, 4) => Some(0x7F), // r2,sp
            (3, 4) => Some(0x80), // fp,sp
            _ => None,
        },
        Opcode::Sb => match (ra, rb) {
            (0, 1) => Some(0x81), // r0,r1
            (0, 2) => Some(0x82), // r0,r2
            (0, 3) => Some(0x83), // r0,fp
            (1, 0) => Some(0x84), // r1,r0
            (1, 2) => Some(0x85), // r1,r2
            (1, 3) => Some(0x86), // r1,fp
            (2, 0) => Some(0x87), // r2,r0
            (2, 1) => Some(0x88), // r2,r1
            (2, 3) => Some(0x89), // r2,fp
            _ => None,
        },
        Opcode::Shl => match (ra, rb) {
            (0, 1) => Some(0x8A), // r0,r1
            (0, 2) => Some(0x8B), // r0,r2
            (1, 0) => Some(0x8C), // r1,r0
            (1, 2) => Some(0x8D), // r1,r2
            (2, 0) => Some(0x8E), // r2,r0
            (2, 1) => Some(0x8F), // r2,r1
            _ => None,
        },
        Opcode::Sra => match (ra, rb) {
            (0, 1) => Some(0x90), // r0,r1
            (0, 2) => Some(0x91), // r0,r2
            (1, 0) => Some(0x92), // r1,r0
            (1, 2) => Some(0x93), // r1,r2
            (2, 0) => Some(0x94), // r2,r0
            (2, 1) => Some(0x95), // r2,r1
            _ => None,
        },
        Opcode::Srl => match (ra, rb) {
            (0, 1) => Some(0x96), // r0,r1
            (0, 2) => Some(0x97), // r0,r2
            (1, 0) => Some(0x98), // r1,r0
            (1, 2) => Some(0x99), // r1,r2
            (2, 0) => Some(0x9A), // r2,r0
            (2, 1) => Some(0x9B), // r2,r1
            _ => None,
        },
        Opcode::Sub => match (ra, rb) {
            (0, 1) => Some(0x9C), // r0,r1
            (0, 2) => Some(0x9D), // r0,r2
            (1, 0) => Some(0x9E), // r1,r0
            (1, 2) => Some(0x9F), // r1,r2
            (2, 0) => Some(0xA0), // r2,r0
            (2, 1) => Some(0xA1), // r2,r1
            _ => None,
        },
        Opcode::SubSp => match (ra, rb) {
            (4, 7) => Some(0xA2), // sp,r7
            _ => None,
        },
        Opcode::Sw => match (ra, rb) {
            (0, 0) => Some(0xA3), // r0,r0
            (0, 1) => Some(0xA4), // r0,r1
            (0, 2) => Some(0xA5), // r0,r2
            (0, 3) => Some(0xA6), // r0,fp
            (1, 0) => Some(0xA7), // r1,r0
            (1, 1) => Some(0xA8), // r1,r1
            (1, 2) => Some(0xA9), // r1,r2
            (1, 3) => Some(0xAA), // r1,fp
            (2, 0) => Some(0xAB), // r2,r0
            (2, 1) => Some(0xAC), // r2,r1
            (2, 2) => Some(0xAD), // r2,r2
            (2, 3) => Some(0xAE), // r2,fp
            _ => None,
        },
        Opcode::Sxt => match (ra, rb) {
            (0, 0) => Some(0xAF), // r0,r0
            (0, 1) => Some(0xB0), // r0,r1
            (0, 2) => Some(0xB1), // r0,r2
            (1, 0) => Some(0xB2), // r1,r0
            (1, 1) => Some(0xB3), // r1,r1
            (1, 2) => Some(0xB4), // r1,r2
            (2, 0) => Some(0xB5), // r2,r0
            (2, 1) => Some(0xB6), // r2,r1
            (2, 2) => Some(0xB7), // r2,r2
            _ => None,
        },
        Opcode::Xor => match (ra, rb) {
            (0, 1) => Some(0xB8), // r0,r1
            (0, 2) => Some(0xB9), // r0,r2
            (1, 0) => Some(0xBA), // r1,r0
            (1, 2) => Some(0xBB), // r1,r2
            (2, 0) => Some(0xBC), // r2,r0
            (2, 1) => Some(0xBD), // r2,r1
            _ => None,
        },
        Opcode::Zxt => match (ra, rb) {
            (0, 0) => Some(0xBE), // r0,r0
            (0, 1) => Some(0xBF), // r0,r1
            (0, 2) => Some(0xC0), // r0,r2
            (1, 0) => Some(0xC1), // r1,r0
            (1, 1) => Some(0xC2), // r1,r1
            (1, 2) => Some(0xC3), // r1,r2
            (2, 0) => Some(0xC4), // r2,r0
            (2, 1) => Some(0xC5), // r2,r1
            (2, 2) => Some(0xC6), // r2,r2
            _ => None,
        },
        Opcode::Invalid => None,
    }
}

/// Encode add register instruction: add ra,rb
pub fn encode_add_reg(ra: u8, rb: u8) -> Option<u8> {
    encode_instruction(Opcode::AddReg, ra, rb)
}

/// Encode add immediate instruction first byte: add ra,imm8
pub fn encode_add_imm(ra: u8) -> Option<u8> {
    // AddImm uses rb=7 as marker in decode ROM
    encode_instruction(Opcode::AddImm, ra, 7)
}

/// Encode mov instruction: mov ra,rb
pub fn encode_mov(ra: u8, rb: u8) -> Option<u8> {
    encode_instruction(Opcode::Mov, ra, rb)
}

/// Encode push instruction: push ra
pub fn encode_push(ra: u8) -> Option<u8> {
    // Push uses rb=4 (sp) in decode ROM
    encode_instruction(Opcode::Push, ra, 4)
}

/// Encode pop instruction: pop ra
pub fn encode_pop(ra: u8) -> Option<u8> {
    // Pop uses rb=4 (sp) in decode ROM
    encode_instruction(Opcode::Pop, ra, 4)
}

/// Encode branch instruction first byte
pub fn encode_branch(opcode: Opcode) -> Option<u8> {
    // Branch instructions use ra=7, rb=7 marker
    encode_instruction(opcode, 7, 7)
}

/// Encode load/store instruction first byte: lb/lbu/lw/sb/sw ra,offset(rb)
pub fn encode_load_store(opcode: Opcode, ra: u8, rb: u8) -> Option<u8> {
    encode_instruction(opcode, ra, rb)
}

/// Encode lc/lcu instruction first byte: lc ra,imm8
pub fn encode_lc(ra: u8, unsigned: bool) -> Option<u8> {
    // Uses rb=7 as marker
    let opcode = if unsigned { Opcode::Lcu } else { Opcode::Lc };
    encode_instruction(opcode, ra, 7)
}

/// Encode la instruction first byte: la ra,addr24
pub fn encode_la(ra: u8) -> Option<u8> {
    // Uses rb=7 as marker
    encode_instruction(Opcode::La, ra, 7)
}

/// Encode sub sp,imm24 first byte
pub fn encode_sub_sp() -> Option<u8> {
    // SubSp uses ra=4 (sp), rb=7 as marker
    encode_instruction(Opcode::SubSp, 4, 7)
}

/// Encode jmp (ra) instruction
pub fn encode_jmp(ra: u8) -> Option<u8> {
    // Jmp uses rb=7 as marker
    encode_instruction(Opcode::Jmp, ra, 7)
}

/// Encode jal ra,(rb) instruction
pub fn encode_jal(ra: u8, rb: u8) -> Option<u8> {
    encode_instruction(Opcode::Jal, ra, rb)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_encode_add_reg() {
        assert_eq!(encode_add_reg(0, 0), Some(0x00)); // add r0,r0
        assert_eq!(encode_add_reg(0, 1), Some(0x01)); // add r0,r1
        assert_eq!(encode_add_reg(1, 0), Some(0x03)); // add r1,r0
    }

    #[test]
    fn test_encode_push_pop() {
        assert_eq!(encode_push(0), Some(0x7D)); // push r0
        assert_eq!(encode_push(1), Some(0x7E)); // push r1
        assert_eq!(encode_pop(0), Some(0x79));  // pop r0
        assert_eq!(encode_pop(1), Some(0x7A));  // pop r1
    }

    #[test]
    fn test_encode_mov() {
        assert_eq!(encode_mov(3, 4), Some(0x65)); // mov fp,sp
        assert_eq!(encode_mov(4, 3), Some(0x69)); // mov sp,fp
        assert_eq!(encode_mov(0, 2), Some(0x57)); // mov r0,r2
    }

    #[test]
    fn test_encode_branch() {
        assert_eq!(encode_branch(Opcode::Bra), Some(0x13));
        assert_eq!(encode_branch(Opcode::Brf), Some(0x14));
        assert_eq!(encode_branch(Opcode::Brt), Some(0x15));
    }

    #[test]
    fn test_encode_lc() {
        assert_eq!(encode_lc(0, false), Some(0x44)); // lc r0,imm
        assert_eq!(encode_lc(1, false), Some(0x45)); // lc r1,imm
        assert_eq!(encode_lc(0, true), Some(0x47));  // lcu r0,imm
    }
}
