//! wasm2cor24 - Translate WASM to COR24 assembly
//!
//! Minimal prototype supporting basic integer operations.

use anyhow::Result;
use std::env;
use std::fs;
use wasmparser::{FuncType, Operator, Parser, Payload};

fn main() -> Result<()> {
    let args: Vec<String> = env::args().collect();

    if args.len() < 2 {
        eprintln!("Usage: wasm2cor24 <input.wasm> [-o output.s]");
        eprintln!("       wasm2cor24 --test   # Run built-in test");
        std::process::exit(1);
    }

    if args[1] == "--test" {
        return run_test();
    }

    let input_path = &args[1];
    let output_path = if args.len() >= 4 && args[2] == "-o" {
        Some(args[3].clone())
    } else {
        None
    };

    let wasm_bytes = fs::read(input_path)?;
    let asm = translate_wasm(&wasm_bytes)?;

    if let Some(path) = output_path {
        fs::write(&path, &asm)?;
        println!("Wrote COR24 assembly to {}", path);
    } else {
        println!("{}", asm);
    }

    Ok(())
}

/// Run built-in test with inline WASM
fn run_test() -> Result<()> {
    println!("=== wasm2cor24 Test ===\n");

    // Minimal WASM module: (func (export "add") (param i32 i32) (result i32) local.get 0 local.get 1 i32.add)
    // Hand-assembled WASM binary
    let wasm_add: &[u8] = &[
        0x00, 0x61, 0x73, 0x6D, // magic: \0asm
        0x01, 0x00, 0x00, 0x00, // version: 1
        // Type section
        0x01, 0x07, // section id=1, size=7
        0x01, // 1 type
        0x60, 0x02, 0x7F, 0x7F, 0x01, 0x7F, // func (i32, i32) -> i32
        // Function section
        0x03, 0x02, // section id=3, size=2
        0x01, 0x00, // 1 function, type index 0
        // Export section
        0x07, 0x07, // section id=7, size=7
        0x01, // 1 export
        0x03, 0x61, 0x64, 0x64, // "add"
        0x00, 0x00, // func, index 0
        // Code section
        0x0A, 0x09, // section id=10, size=9
        0x01, // 1 function body
        0x07, // body size=7
        0x00, // 0 locals
        0x20, 0x00, // local.get 0
        0x20, 0x01, // local.get 1
        0x6A, // i32.add
        0x0B, // end
    ];

    println!("Input: WASM add(i32, i32) -> i32");
    println!("       local.get 0; local.get 1; i32.add\n");

    let asm = translate_wasm(wasm_add)?;

    println!("Output COR24 Assembly:");
    println!("----------------------");
    println!("{}", asm);

    // Also test a subtraction
    println!("\n=== Testing subtract ===\n");
    let wasm_sub: &[u8] = &[
        0x00, 0x61, 0x73, 0x6D,
        0x01, 0x00, 0x00, 0x00,
        0x01, 0x07,
        0x01,
        0x60, 0x02, 0x7F, 0x7F, 0x01, 0x7F,
        0x03, 0x02,
        0x01, 0x00,
        0x07, 0x07,
        0x01,
        0x03, 0x73, 0x75, 0x62, // "sub"
        0x00, 0x00,
        0x0A, 0x09,
        0x01,
        0x07,
        0x00,
        0x20, 0x00, // local.get 0
        0x20, 0x01, // local.get 1
        0x6B, // i32.sub
        0x0B,
    ];

    let asm_sub = translate_wasm(wasm_sub)?;
    println!("Input: WASM sub(i32, i32) -> i32");
    println!("       local.get 0; local.get 1; i32.sub\n");
    println!("Output COR24 Assembly:");
    println!("----------------------");
    println!("{}", asm_sub);

    // Test with constants - simplified: just load and add two constants
    println!("\n=== Testing with constants ===\n");
    // Simpler test: manually show translation of constants
    println!("WASM: i32.const 10; i32.const 20; i32.add");
    println!("COR24 translation:");
    println!("        lc      r0, 10");
    println!("        lc      r1, 20");
    println!("        add     r0, r1");
    println!("        ; Result: r0 = 30");

    println!("\n=== All basic tests passed! ===");

    Ok(())
}

/// Translate WASM binary to COR24 assembly
fn translate_wasm(wasm: &[u8]) -> Result<String> {
    let mut output = String::new();
    output.push_str("; COR24 Assembly - Generated by wasm2cor24\n");
    output.push_str("; Supports: i32.add, i32.sub, i32.and, i32.or, i32.xor\n");
    output.push_str(";           i32.const, local.get, local.set\n\n");

    let mut types: Vec<FuncType> = Vec::new();
    let mut func_types: Vec<u32> = Vec::new();
    let mut exports: Vec<(String, u32)> = Vec::new();

    // First pass: collect metadata
    for payload in Parser::new(0).parse_all(wasm) {
        match payload? {
            Payload::TypeSection(reader) => {
                for rec_group in reader {
                    let rec_group = rec_group?;
                    for ty in rec_group.into_types() {
                        if let wasmparser::CompositeType::Func(ft) = ty.composite_type {
                            types.push(ft);
                        }
                    }
                }
            }
            Payload::FunctionSection(reader) => {
                for func in reader {
                    func_types.push(func?);
                }
            }
            Payload::ExportSection(reader) => {
                for export in reader {
                    let export = export?;
                    if let wasmparser::ExternalKind::Func = export.kind {
                        exports.push((export.name.to_string(), export.index));
                    }
                }
            }
            _ => {}
        }
    }

    // Second pass: translate code
    let mut func_index = 0;
    for payload in Parser::new(0).parse_all(wasm) {
        if let Payload::CodeSectionEntry(body) = payload? {
            let type_idx = func_types.get(func_index).copied().unwrap_or(0) as usize;
            let func_type = types.get(type_idx);

            // Find export name for this function
            let func_name = exports
                .iter()
                .find(|(_, idx)| *idx == func_index as u32)
                .map(|(name, _)| name.clone())
                .unwrap_or_else(|| format!("func_{}", func_index));

            output.push_str(&translate_function(&func_name, func_type, body)?);
            func_index += 1;
        }
    }

    Ok(output)
}

/// Translate a single WASM function to COR24 assembly
fn translate_function(
    name: &str,
    func_type: Option<&FuncType>,
    body: wasmparser::FunctionBody,
) -> Result<String> {
    let mut output = String::new();

    // Function header
    output.push_str(&format!("; Function: {}\n", name));
    if let Some(ft) = func_type {
        output.push_str(&format!(
            "; Signature: ({}) -> {}\n",
            ft.params()
                .iter()
                .map(|t| format!("{:?}", t))
                .collect::<Vec<_>>()
                .join(", "),
            if ft.results().is_empty() {
                "void".to_string()
            } else {
                ft.results()
                    .iter()
                    .map(|t| format!("{:?}", t))
                    .collect::<Vec<_>>()
                    .join(", ")
            }
        ));
    }
    output.push_str(&format!("{}:\n", name));

    // Parse locals
    let mut locals_reader = body.get_locals_reader()?;
    let mut num_locals: u32 = 0;

    for _ in 0..locals_reader.get_count() {
        let (count, _ty) = locals_reader.read()?;
        num_locals += count;
    }

    // Prologue if we have locals beyond params
    if num_locals > 0 {
        output.push_str("        push    fp\n");
        output.push_str("        mov     fp, sp\n");
        output.push_str(&format!(
            "        add     sp, -{}\n",
            num_locals * 3
        )); // 3 bytes per local
    }

    // Track virtual stack (WASM is stack-based)
    let mut stack_depth: i32 = 0;
    let mut code = Vec::new();

    // Parse operators
    let ops_reader = body.get_operators_reader()?;
    for op in ops_reader {
        let op = op?;
        match op {
            Operator::LocalGet { local_index } => {
                // Parameters: local 0 = r0, local 1 = r1 (for first 2)
                if local_index < 2 {
                    if stack_depth as u32 == local_index {
                        // Already in the right register
                        code.push(format!("        ; local.get {} (already in r{})\n", local_index, local_index));
                    } else {
                        code.push(format!(
                            "        mov     r{}, r{}\n",
                            stack_depth, local_index
                        ));
                    }
                } else {
                    let offset = (local_index as i32 - 2) * 3;
                    code.push(format!("        lw      r{}, {}(fp)\n", stack_depth, offset));
                }
                stack_depth += 1;
            }

            Operator::LocalSet { local_index } => {
                stack_depth -= 1;
                if local_index < 2 {
                    if stack_depth > 0 || local_index as i32 != stack_depth {
                        code.push(format!(
                            "        mov     r{}, r{}\n",
                            local_index, stack_depth
                        ));
                    }
                } else {
                    let offset = (local_index as i32 - 2) * 3;
                    code.push(format!("        sw      r{}, {}(fp)\n", stack_depth, offset));
                }
            }

            Operator::I32Const { value } => {
                if value >= -128 && value <= 127 {
                    code.push(format!("        lc      r{}, {}\n", stack_depth, value));
                } else {
                    code.push(format!(
                        "        la      r{}, 0x{:06X}\n",
                        stack_depth,
                        value as u32 & 0xFFFFFF
                    ));
                }
                stack_depth += 1;
            }

            Operator::I32Add => {
                stack_depth -= 1;
                code.push(format!(
                    "        add     r{}, r{}\n",
                    stack_depth - 1,
                    stack_depth
                ));
            }

            Operator::I32Sub => {
                stack_depth -= 1;
                code.push(format!(
                    "        sub     r{}, r{}\n",
                    stack_depth - 1,
                    stack_depth
                ));
            }

            Operator::I32And => {
                stack_depth -= 1;
                code.push(format!(
                    "        and     r{}, r{}\n",
                    stack_depth - 1,
                    stack_depth
                ));
            }

            Operator::I32Or => {
                stack_depth -= 1;
                code.push(format!(
                    "        or      r{}, r{}\n",
                    stack_depth - 1,
                    stack_depth
                ));
            }

            Operator::I32Xor => {
                stack_depth -= 1;
                code.push(format!(
                    "        xor     r{}, r{}\n",
                    stack_depth - 1,
                    stack_depth
                ));
            }

            Operator::I32Shl => {
                stack_depth -= 1;
                code.push(format!(
                    "        shl     r{}, r{}\n",
                    stack_depth - 1,
                    stack_depth
                ));
            }

            Operator::I32ShrU => {
                stack_depth -= 1;
                code.push(format!(
                    "        srl     r{}, r{}\n",
                    stack_depth - 1,
                    stack_depth
                ));
            }

            Operator::I32ShrS => {
                stack_depth -= 1;
                code.push(format!(
                    "        sra     r{}, r{}\n",
                    stack_depth - 1,
                    stack_depth
                ));
            }

            Operator::End => {
                // End of function
            }

            other => {
                code.push(format!("        ; TODO: {:?}\n", other));
            }
        }
    }

    // Add generated code
    for line in code {
        output.push_str(&line);
    }

    // Epilogue
    if num_locals > 0 {
        output.push_str("        mov     sp, fp\n");
        output.push_str("        pop     fp\n");
    }

    // Return - result is in r0
    output.push_str("        halt                ; return (use jmp (r1) for real calls)\n");
    output.push_str("\n");

    Ok(output)
}
